// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXwgdU_SYXCXaCbrIVNeQNYcQ7QE6tsqw',
    appId: '1:333152839693:web:ec7e216bb73f8915044d44',
    messagingSenderId: '333152839693',
    projectId: 'flutter-a4b43',
    authDomain: 'flutter-a4b43.firebaseapp.com',
    storageBucket: 'flutter-a4b43.appspot.com',
    measurementId: 'G-KTHZFK6YHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2063W2aUwgIq72Wr4w82o9e-VyA-7K4',
    appId: '1:333152839693:android:68bb868588a29cf4044d44',
    messagingSenderId: '333152839693',
    projectId: 'flutter-a4b43',
    storageBucket: 'flutter-a4b43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxHn7K7Dtv-D5xzBnjvKkIz-ghNmsJGP4',
    appId: '1:333152839693:ios:ad16d2aac08d89a8044d44',
    messagingSenderId: '333152839693',
    projectId: 'flutter-a4b43',
    storageBucket: 'flutter-a4b43.appspot.com',
    iosClientId: '333152839693-dubq52c3iot4192mj9c7i1vc49fq3qak.apps.googleusercontent.com',
    iosBundleId: 'com.example.readData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxHn7K7Dtv-D5xzBnjvKkIz-ghNmsJGP4',
    appId: '1:333152839693:ios:ad16d2aac08d89a8044d44',
    messagingSenderId: '333152839693',
    projectId: 'flutter-a4b43',
    storageBucket: 'flutter-a4b43.appspot.com',
    iosClientId: '333152839693-dubq52c3iot4192mj9c7i1vc49fq3qak.apps.googleusercontent.com',
    iosBundleId: 'com.example.readData',
  );
}
